version: '3.1'
services:
    app:
        image: go_rest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
           DATABASE_HOST: dbPostgres
           REDIS_HOST: redis
        depends_on:
            - dbPostgres
        ports:
            - '9000:9000'

    adminer:
        image:
            dockette/adminer:full
        restart:
            always
        ports:
            - "8088:80"

    dbPostgres:
        image: postgres:12
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: apidb
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        container_name: "redis"
        image: redis
        volumes:
          - redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

volumes:
    postgres: {}
    redis: {}
